In [38]:
#numpy is used for the matrix calculations and the concept of array
import numpy as np
j=[4,6,2,8,9]
j

[4, 6, 2, 8, 9]

In [ ]:
1) numpy                      array operations
2) pandas                     data manipulation and analysis
3) matplotlib and seaborn     graphical analysis
4) sklearn                    machine learning algorithms and techniques
5) statsmodels                statistical analysis
6) scipy                      statistical analysis

In [134]:
j=[2,5,4,2,1,3]
j

[2, 5, 4, 2, 1, 3]

In [136]:
d=np.array(j)
d

array([2, 5, 4, 2, 1, 3])

In [10]:
tuple(j)

(2, 5, 4, 2, 1, 3, 7)

In [24]:
type(d)

numpy.ndarray

In [26]:
d

array([2, 5, 4, 2, 1, 3, 7])

In [28]:
d.shape

(7,)

In [30]:
#list doesn't have any shape
j.shape

AttributeError: 'list' object has no attribute 'shape'

In [32]:
d.ndim

1

In [88]:
d.reshape

<function ndarray.reshape>

In [36]:
d.size

7

In [66]:
s=[[4,6,8,9,2],[5,3,5,7,5],[34,67,98,94,78],[23,4,5,67,78],[98,45,32,34,54]]
s

[[4, 6, 8, 9, 2],
 [5, 3, 5, 7, 5],
 [34, 67, 98, 94, 78],
 [23, 4, 5, 67, 78],
 [98, 45, 32, 34, 54]]

In [68]:
arr1=np.array(s)
arr1

array([[ 4,  6,  8,  9,  2],
       [ 5,  3,  5,  7,  5],
       [34, 67, 98, 94, 78],
       [23,  4,  5, 67, 78],
       [98, 45, 32, 34, 54]])

In [70]:
type(s)

list

In [72]:
type(arr1)

numpy.ndarray

In [74]:
arr1.shape

(5, 5)

In [76]:
arr1.size

25

In [78]:
arr1.ndim

2

In [167]:
arr1.reshape

<function ndarray.reshape>

In [138]:
h=d.reshape(2,3)
h

array([[2, 5, 4],
       [2, 1, 3]])

In [142]:
h.size

6

In [144]:
h.shape

(2, 3)

In [146]:
h.ndim

2

In [148]:
w=h.reshape(3,2)
w

array([[2, 5],
       [4, 2],
       [1, 3]])

In [150]:
w.shape


(3, 2)

In [152]:
w.size

6

In [154]:
w.ndim

2

In [169]:
m=[4,6,7,8,9,1,2,3,11,12]
m

[4, 6, 7, 8, 9, 1, 2, 3, 11, 12]

In [173]:
range(3,13,)

range(3, 13)

In [175]:
list(range(3,13,2))

[3, 5, 7, 9, 11]

In [177]:
list(range(3,13,3))

[3, 6, 9, 12]

In [179]:
range(5,500,)

range(5, 500)

In [185]:
list(range(5,500,100))

[5, 105, 205, 305, 405]

In [197]:
tuple(range(5,520,110))

(5, 115, 225, 335, 445)

In [199]:
list(range(-10,1))

[-10, -9, -8, -7, -6, -5, -4, -3, -2, -1, 0]

In [201]:
range(-1,-10)

range(-1, -10)

In [209]:
list(range(-1,-10,-1))

[-1, -2, -3, -4, -5, -6, -7, -8, -9]

In [211]:
list(range(-1,-10,-2))

[-1, -3, -5, -7, -9]

In [213]:
list(range(-1,-10,-5))

[-1, -6]

In [215]:
list(range(10,-10,-1))

[10, 9, 8, 7, 6, 5, 4, 3, 2, 1, 0, -1, -2, -3, -4, -5, -6, -7, -8, -9]

In [217]:
list(range(10,-10,-3))

[10, 7, 4, 1, -2, -5, -8]

In [219]:
list(range(-1,-10,-1))

[-1, -2, -3, -4, -5, -6, -7, -8, -9]

In [229]:
list(range(-1,-10,-1))

[-1, -2, -3, -4, -5, -6, -7, -8, -9]

In [231]:
[2.5,3,3.5,4,4.5]

[2.5, 3, 3.5, 4, 4.5]

In [233]:
range(2.5,5,0.5)

TypeError: 'float' object cannot be interpreted as an integer

In [235]:
#we can provide integer values and float values
np.arange(2.5,5,0.5)

array([2.5, 3. , 3.5, 4. , 4.5])

In [239]:
2.5,5,0.5

(2.5, 5, 0.5)

In [243]:
np.arange(5,50,5)

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45])

In [247]:
for i in range(5,50,5):
    print("data",i)

data 5
data 10
data 15
data 20
data 25
data 30
data 35
data 40
data 45


In [249]:
j=[5,87,98,45,56,98,43,32,12,23]
j

[5, 87, 98, 45, 56, 98, 43, 32, 12, 23]

In [253]:
list(range(5,23))

[5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22]

In [255]:
j=[5,87,98,45,56,98,43,32,12,23]
j

[5, 87, 98, 45, 56, 98, 43, 32, 12, 23]

In [280]:
y=[]
x=[]
for i in range(len(j)):
    if i % 2 == 0:
        x.append(j[i])
    else:
        y.append(j[i])



In [282]:
x

[5, 98, 56, 43, 12]

In [284]:
y

[87, 45, 98, 32, 23]