In [1]:
from pandas import read_csv
import seaborn as sns
import numpy as np
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2,f_regression,f_classif
dataframe=sns.load_dataset('tips')
dataframe

total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [2]:
from sklearn.preprocessing import LabelEncoder
lb=LabelEncoder()
dataframe['sex']=lb.fit_transform(dataframe['sex'])
dataframe['smoker']=lb.fit_transform(dataframe['smoker'])
dataframe['day']=lb.fit_transform(dataframe['day'])
dataframe['time']=lb.fit_transform(dataframe['time'])

In [3]:
dataframe

total_bill   tip  sex  smoker  day  time  size
0         16.99  1.01    0       0    2     0     2
1         10.34  1.66    1       0    2     0     3
2         21.01  3.50    1       0    2     0     3
3         23.68  3.31    1       0    2     0     2
4         24.59  3.61    0       0    2     0     4
..          ...   ...  ...     ...  ...   ...   ...
239       29.03  5.92    1       0    1     0     3
240       27.18  2.00    0       1    1     0     2
241       22.67  2.00    1       1    1     0     2
242       17.82  1.75    1       0    1     0     2
243       18.78  3.00    0       0    3     0     2

[244 rows x 7 columns]

In [7]:
dataframe.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   total_bill  244 non-null    float64
 1   tip         244 non-null    float64
 2   sex         244 non-null    int64  
 3   smoker      244 non-null    int64  
 4   day         244 non-null    int64  
 5   time        244 non-null    int64  
 6   size        244 non-null    int64  
dtypes: float64(2), int64(5)
memory usage: 13.5 KB


In [9]:
#x is target column and y is independent one
X = dataframe.drop('tip',axis=1)
Y = dataframe.tip

In [11]:
X

total_bill  sex  smoker  day  time  size
0         16.99    0       0    2     0     2
1         10.34    1       0    2     0     3
2         21.01    1       0    2     0     3
3         23.68    1       0    2     0     2
4         24.59    0       0    2     0     4
..          ...  ...     ...  ...   ...   ...
239       29.03    1       0    1     0     3
240       27.18    0       1    1     0     2
241       22.67    1       1    1     0     2
242       17.82    1       0    1     0     2
243       18.78    0       0    3     0     2

[244 rows x 6 columns]

In [13]:
Y

0      1.01
1      1.66
2      3.50
3      3.31
4      3.61
       ... 
239    5.92
240    2.00
241    2.00
242    1.75
243    3.00
Name: tip, Length: 244, dtype: float64

In [15]:
#to select the best columns among all the columns we can use selectkbest method
test = SelectKBest(score_func=f_regression, k=3).fit(X,Y)
test

SelectKBest(k=3, score_func=<function f_regression at 0x13944ccc0>)

In [17]:

#to get the statistics(scores) of our hypothesis tests
test.scores_

array([2.03357723e+02, 1.92615456e+00, 8.50601355e-03, 3.22744400e-02,
       3.63381548e+00, 7.61754260e+01])

In [19]:
#to get the round figure
np.round(test.scores_,3)

array([2.03358e+02, 1.92600e+00, 9.00000e-03, 3.20000e-02, 3.63400e+00,
       7.61750e+01])

In [21]:
dataframe.columns

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size'], dtype='object')

In [23]:
np.round(test.pvalues_,3)

array([0.   , 0.166, 0.927, 0.858, 0.058, 0.   ])

In [25]:
#to get the names of best columns
test.get_feature_names_out()

array(['total_bill', 'time', 'size'], dtype=object)

In [27]:
#for regression: f_regression, mutual_info_regression
#for classification: chi2, f_classif, mutual_info_classif

In [29]:
df=sns.load_dataset('iris')
df.head()

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [31]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB


In [33]:
from sklearn.preprocessing import LabelEncoder
lb=LabelEncoder()
df['species']=lb.fit_transform(df['species'])

In [35]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    int64  
dtypes: float64(4), int64(1)
memory usage: 6.0 KB


In [37]:
X = df.drop('species',axis=1)
Y = df['species']

In [39]:
X

sepal_length  sepal_width  petal_length  petal_width
0             5.1          3.5           1.4          0.2
1             4.9          3.0           1.4          0.2
2             4.7          3.2           1.3          0.2
3             4.6          3.1           1.5          0.2
4             5.0          3.6           1.4          0.2
..            ...          ...           ...          ...
145           6.7          3.0           5.2          2.3
146           6.3          2.5           5.0          1.9
147           6.5          3.0           5.2          2.0
148           6.2          3.4           5.4          2.3
149           5.9          3.0           5.1          1.8

[150 rows x 4 columns]

In [41]:
Y

0      0
1      0
2      0
3      0
4      0
      ..
145    2
146    2
147    2
148    2
149    2
Name: species, Length: 150, dtype: int64

In [43]:
chi = SelectKBest(score_func=chi2, k=2).fit(X,Y)
chi

SelectKBest(k=2, score_func=<function chi2 at 0x13944ca40>)

In [45]:
chi.scores_

array([ 10.81782088,   3.7107283 , 116.31261309,  67.0483602 ])

In [47]:
np.round(chi.scores_,2)

array([ 10.82,   3.71, 116.31,  67.05])

In [49]:
df.columns

Index(['sepal_length', 'sepal_width', 'petal_length', 'petal_width',
       'species'],
      dtype='object')

In [51]:
np.round(chi.pvalues_,2)

array([0.  , 0.16, 0.  , 0.  ])

In [53]:
chi.get_feature_names_out()

array(['petal_length', 'petal_width'], dtype=object)

In [55]:
#iloc is used for indexing ans slicing
x=df.iloc[:,0:4]
x

sepal_length  sepal_width  petal_length  petal_width
0             5.1          3.5           1.4          0.2
1             4.9          3.0           1.4          0.2
2             4.7          3.2           1.3          0.2
3             4.6          3.1           1.5          0.2
4             5.0          3.6           1.4          0.2
..            ...          ...           ...          ...
145           6.7          3.0           5.2          2.3
146           6.3          2.5           5.0          1.9
147           6.5          3.0           5.2          2.0
148           6.2          3.4           5.4          2.3
149           5.9          3.0           5.1          1.8

[150 rows x 4 columns]

In [57]:
chi.pvalues_

array([4.47651499e-03, 1.56395980e-01, 5.53397228e-26, 2.75824965e-15])

In [61]:
df.columns[np.where(chi.get_support(indices=True))]

Index(['sepal_length', 'sepal_width'], dtype='object')